server:
  port: 7002

spring:
  application:
    name: cloud-eureka-service

eureka:
  instance:
    instance-id: eureka7002
    hostname: eureka7002.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
