server:
  port: 8001



spring:
  application:
    name: cloud-provider-service
  zipkin: # Zipkin config
    base-url: http://localhost:9411
  slenth:
    sampler:
      probability: 1

eureka:
  instance:
    instance-id: payment8001
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka