server:
  port: 7001

spring:
  application:
    name: cloud-eureka-service

eureka:
  instance:
    instance-id: eureka7001
    hostname: eureka7001.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
