server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: order_group  # identify there the tx service group, should be same with 'vgroupMapping.order_group' in file.conf in seata server
    nacos:
      discovery:
        server-addr: 192.168.1.2:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.2:3306/seata_order
    username: sam01
    password: 6fcukeLI

seata:
  enable-auto-data-source-proxy: false

mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml