server:
  port: 9001


spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.31:8848  # need to be changed when ip changed after bounce

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"