server:
  port: 83


spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.31:8848  # need to be changed when ip changed after bounce

service-url:
  nacos-provider-service: http://nacos-payment-provider

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"