server:
  port: 3355

spring:
  config:
    import: configserver:http://localhost:3344
  application:
    name: config-client
  cloud:
    config:
      label: main
      name: config
      profile: dev
      uri: http://localhost:3344
  # rabbitmq for config distribute
  rabbitmq:
    host: 192.168.1.10
    port: 5672
    username: admin
    password: 6fcukeLI




# rabbitmq, expose bus refresh endpoint
management:
  endpoints:
    web:
      exposure:
        include: "*"


# eureka
eureka:
  instance:
    instance-id: client-config3355
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


